Replace BlastN by Minimap2 splice.
sanger-tol/readmapping pull request #104
Opened 2024-08-06 07:57 UTC by reichan1998

Fixes #66
- Replace BlastN step in PacBio read filtering by [Minimap2 splice](https://github.com/lh3/minimap2/blob/master/README.md#map-long-splice).
- Change `vector_db` in `nextflow.config` from `vectorDB.tar.gz` to `pacbio_vectorDB.fasta`.

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/sanger-tol/readmapping/tree/master/.github/CONTRIBUTING.md)
- [x] Make sure your code lints (`nf-core lint`).
- [x] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [x] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

2024-08-07 12:20 UTC, tkchafin requested changes
I think you should be able to do this using the existing [minimap2_align](https://nf-co.re/modules/minimap2_align/) nf-core module, and setting `splice` using `ext.args` as you are currently doing? Should also check if we can store and provide a gzipped fasta, and if there is any benefit to indexing it before running.

2024-08-07 14:19 UTC, reichan1998 commented
Thank you for your feedback! I will try and enhance the process.

2024-08-09 13:11 UTC, reichan1998 commented
Hi @tkchafin,

I have set the `splice` option using `ext.args` in the nf-core module `minimap2 align`. Checking the `splice` command input options, I found that it can accept both gzipped files of `vector_db` and `fasta` files. I indexed `vector_db` before running the analysis, but it doesn't seem to have had a significant impact on running time or resource usage. I have attached [the execution report ](https://drive.google.com/file/d/1B1sagd25feCUHO-JF6aQ3BB8ofdvLfYI/view?usp=drive_link)for your review.

2024-08-12 08:51 UTC, tkchafin commented on assets/pacbio_vectorDB.fasta
Let's include this as "vectorDB.fasta.gz" since gz input is accepted

2024-08-12 08:51 UTC, tkchafin commented on conf/modules.config
You can import and refer to this instance of MINIMAP2_ALIGN under an alias (e.g., "MINIMAP2_SPLICE") to help differentiate that it is being run in a different mode -- well make readability better in the pipeline and also possibly make it a little less likely to introduce mistakes in the `modules.config`

2024-08-12 08:51 UTC, tkchafin commented on docs/output.md
Possibly specify the use of splice

2024-08-12 08:51 UTC, tkchafin commented on nextflow.config
after changing file be sure to update path here vectorFB.fasta.gz

2024-08-12 08:51 UTC, tkchafin commented on nextflow_schema.json
here as well

2024-08-12 08:51 UTC, tkchafin commented on modules/nf-core/minimap2/align/main.nf
We should not be making changes to any nf-core modules, because these will be overwritten when the module updates. Any specific runtime parameters should only be passed using the `ext` in `modules.config`.

2024-08-12 08:56 UTC, tkchafin commented
I don't think you should need to modify the accepted arguments for `nf-core/minimap2_align`, because in the case we are using it in `pacbio_filter.nf` would the database not be passed using the already existing reference argument? You should just be able to format that using `map` and pass as it is. In practice we do not like to make any changes to the nf-core modules because these will be overwritten down the line when running updates

2024-08-13 06:41 UTC, reichan1998 commented
Thank you very much for your feedback @tkchafin. I'm working on it now.

2024-08-14 09:43 UTC, reichan1998 commented
Thank you, Tyler, for pointing this out. I was also confused about the preset.
I changed `task.ext.args` to `-x splice:hq Long-read splice alignment for PacBio CCS reads (-xsplice -C5 -O6,24 -B4)` in [the commit](https://github.com/sanger-tol/readmapping/pull/104/commits/54bda0f5e250d6acc550b139cd23ebc8094dd886#diff-bf809c928cb10b54d251dec8a140a2d5505150f97175d8d7b51dda9cc57971fe) following the document [here](https://lh3.github.io/minimap2/minimap2.html). 
Here is `-x splice:hq` for `mMelMel3_T4`:
```
m64094_200911_174739/112397133/ccs	16666	16608	16665	+	bcAd1022T	78	3	60	57	57	16	tp:A:P	cm:i:16	s1:i:57	s2:i:47	dv:f:0.0040	rl:i:0
m64094_200911_174739/112397133/ccs	16666	16618	16665	+	bcAd1020T	78	13	60	47	47	0	tp:A:S	cm:i:13	s1:i:47	dv:f:0.0049	rl:i:0
m64094_200911_174739/112397133/ccs	16666	16620	16665	+	bcAd1016T	78	15	60	45	45	0	tp:A:S	cm:i:12	s1:i:45	dv:f:0.0053	rl:i:0
m64094_200911_174739/112397133/ccs	16666	16620	16665	+	bcAd1015T	78	15	60	45	45	0	tp:A:S	cm:i:12	s1:i:45	dv:f:0.0053	rl:i:0
m64094_200911_174739/112397133/ccs	16666	16620	16665	+	bcAd1011T	78	15	60	45	45	0	tp:A:S	cm:i:12	s1:i:45	dv:f:0.0053	rl:i:0
m64094_200911_174739/112397133/ccs	16666	16620	16665	+	bcAd1001T	78	15	60	45	45	0	tp:A:S	cm:i:12	s1:i:45	dv:f:0.0053	rl:i:0
m64094_200911_174739/125897038/ccs	12653	81	152	-	bcAd1022T	78	3	74	71	71	15	tp:A:P	cm:i:20	s1:i:71	s2:i:62	dv:f:0	rl:i:0
m64094_200911_174739/125897038/ccs	12653	3	74	-	bcAd1022T	78	3	74	71	71	35	tp:A:P	cm:i:20	s1:i:71	s2:i:50	dv:f:0	rl:i:0
m64094_200911_174739/125897038/ccs	12653	17	125	-	MG551957.1	4034	2	2049	72	2047	0	tp:A:S	cm:i:18	s1:i:62	dv:f:0.0290	rl:i:0
m64094_200911_174739/125897038/ccs	12653	92	142	-	bcAd1020T	78	13	63	50	50	0	tp:A:S	cm:i:14	s1:i:50	dv:f:0	rl:i:0
m64094_200911_174739/125897038/ccs	12653	14	64	-	bcAd1020T	78	13	63	50	50	0	tp:A:S	cm:i:14	s1:i:50	dv:f:0	rl:i:0
m64094_200911_174739/125897038/ccs	12653	14	62	-	bcAd1016T	78	15	63	48	48	0	tp:A:S	cm:i:13	s1:i:48	dv:f:0	rl:i:0
m64094_200911_174739/125897038/ccs	12653	92	140	-	bcAd1017T	78	15	63	48	48	0	tp:A:S	cm:i:13	s1:i:48	dv:f:0	rl:i:0
 
```
I have tested with `-x map-hifi` and here is its result for `mMelMel3_T4`:
```
m64094_200911_174739/112397133/ccs	16666	16606	16649	+	bcAd1022T	78	1	44	43	43	3	tp:A:P	cm:i:3	s1:i:43	s2:i:0	dv:f:0.0150	rl:i:0
m64094_200911_174739/125897038/ccs	12653	93	154	-	bcAd1022T	78	1	62	61	61	22	tp:A:P	cm:i:4	s1:i:61	s2:i:0	dv:f:0	rl:i:0
m64094_200911_174739/125897038/ccs	12653	15	76	-	bcAd1022T	78	1	62	61	61	22	tp:A:P	cm:i:4	s1:i:61	s2:i:0	dv:f:0	rl:i:0
```
They're different but the sequences needs to be filtered might be the same in both case (`m64094_200911_174739/112397133/ccs` and `m64094_200911_174739/125897038/ccs`)

2024-08-20 10:43 UTC, reichan1998 commented
Hi @tkchafin, here's the blocklist result by BLASTN after filtering.
```
m64094_200911_174739/112397133/ccs
m64094_200911_174739/118490605/ccs
m64094_200911_174739/122815136/ccs
m64094_200911_174739/125897038/ccs
m64094_200911_174739/1311016/ccs
m64094_200911_174739/147720881/ccs
m64094_200911_174739/155451773/ccs
m64094_200911_174739/158007639/ccs
m64094_200911_174739/22743255/ccs
m64094_200911_174739/30081129/ccs
m64094_200911_174739/77136980/ccs
```

2024-09-10 12:03 UTC, tkchafin commented
Closing as we have determined minimap2 splice to not work as an alternative. Opening new ticket to explore alternatives https://github.com/sanger-tol/readmapping/issues/114

2024-09-10 12:03 UTC, closed without merging